from enum import Enum


class LogLevel(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class EventType(Enum):
    AUTHENTICATION = "AUTHENTICATION"  # e.g., LOGIN, LOGOUT
    SECURITY = "SECURITY"  # e.g., PASSWORD_RESET, SECURITY_QUESTION_ANSWER
    TRANSACTION = "TRANSACTION"  # e.g., DEPOSIT, WITHDRAWAL
    DATA_ACCESS = "DATA_ACCESS"  # e.g., READ
    DATA_MODIFICATION = "DATA_MODIFICATION"  # e.g., CREATE, UPDATE, DELETE
    SYSTEM = "SYSTEM"  # e.g., SHUTDOWN, RESTART
